### PR TITLE
Prompt app update & other fixes

### LINKED ISSUE #15: Prompt the user to update the app
Eventually we are going to have conflicts between the api and the app version. Prompt the user to update the app in such cases.

We could do this in two ways:
 - We set up [remote config](https://rnfirebase.io/remote-config/usage) and update the versions in firebase console.
 - The API accepts an header with the client app version and throws a specific status code that we will only use in the app for such case.

Let's discuss this.

cc @s1moe2 @a31859

### LINKED ISSUE #22: [android] Error: Tried to change the navigation bar while not attached to an Activity
This happen when taped in a notification with the app killed on android.

I would suggest that when implemented `setBackgroundMessageHandler` it could be the cause of the issue, but there is reports of the app being freeze on splash screen before this implementation. So the cause could be when we changed the main activity to exported.

Either way the error comes from [this function call](https://github.com/Cloudoki/appdoki-rn/blob/master/src/store/preferences/index.ts#L63).

### PR DESCRIPTION
**Pull request by mstrk**
## Progress
- [x] rename screen components to have a `Screen` suffix, this will minimise confusion on imports.
- [x] move state event keys to it's own file, this will minimise require cycles. NOTE: require cycles are not bad per se, but we incur on the risk of the values are not initialised at the time they are needed.
- [x] Fade animation component.
- [x] Slide animation component.
- [x] Add remote config logic. Only version configuration are required for now.
- [x] Check version from remote config and prompt the user with a modal to update his app, closes #15.
- [x] Fix unhandled promise rejection that freezes the app on splash screen when trying to change navigation bar on android, closes #22.

### CODE REVIEW

File: src/screens/Login/index.tsx [hunk 1]
```diff
@@ -1,24 +1,71 @@
...
+      const newVersionAvailable = semver.gt(latestVersion, appConfig.version)
+
+      // Show a dialog to the user if we found that the user is not in a stable version
+      if (newVersionAvailable) {
+        navigation.navigate('Dialog', {
+          title: 'Update version',
+          confirmText: 'update',
+          onConfirm: async () => {
+            try {
+              // await Linking.openURL(Platform.OS === 'ios' ? storeLinks.ios : storeLinks.android)
```
Comment (mstrk) [inline src/screens/Login/index.tsx:50]: This is commented on purpose I left an example on how we can handle this when we have a first app in the stores.

**Review by a31859 — APPROVED** [review]
